config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"

  resources :posts
  match 'blobs/:signed_id/*filename', to: 'blobs#show', via: [:get, :post]
  delete 'attachments/:signed_id/*filename', to: 'attachments#destroy'
  resources :attachments, only: [:destroy], as: :destroy_attachment
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    has_rich_text :body

    has_one_attached :main_image
    has_many_attached :other_images

    def attach_other_images(signed_blob_id)
      blob = ActiveStorage::Blob.find_signed(signed_blob_id)
      return other_images.attach(signed_blob_id) unless blob.present?

      other_images.attach(blob.signed_id) unless other_images.attachments.map(&:blob_id).include?(blob.id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blobs_controller.rb
class BlobsController < ActiveStorage::BlobsController
    def show
      return super unless @blob.image?
  
      redirect_to @blob.variant(resize: '250x250').processed.service_url(disposition: params[:disposition])
    end
  end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :find_post, only: [:edit, :update, :show, :delete]

  # Index action to render all posts
  def index
    @posts = Post.all
  end

  # New action for creating post
  def new
    @post = Post.new
  end

  # Create action saves the post into database
  def create
    @post = Post.new(post_params)
    if @post.save!
      flash[:notice] = "Successfully created post!"
      redirect_to post_path(@post)
    else
      flash[:alert] = "Error creating new post!"
      render :new
    end
  end

  # Edit action retrives the post and renders the edit page
  def edit
  end

  # Update action updates the post with the new information
  def update
    if @post.update_attributes(post_params)
      flash[:notice] = "Successfully updated post!"
      redirect_to post_path(@post)
    else
      flash[:alert] = "Error updating post!"
      render :edit
    end
  end

  # The show action renders the individual post after retrieving the the id
  def show
  end

  # The destroy action removes the post permanently from the database
  def destroy
    if @post.destroy
      flash[:notice] = "Successfully deleted post!"
      redirect_to posts_path
    else
      flash[:alert] = "Error updating post!"
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :main_image, other_images: [])
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
     <%= link_to "Download", rails_blob_path(blob, disposition: "attachment") %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<% post = @post%>
<%= form_with(model: post, local: true) do |form| %>
<% if post.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
        <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<% if post.id? %>
<%= tag.input type: 'hidden', name: 'post_id', value: post.id, id: 'post-id' %>
<% end %>

<div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
</div>

<div class="field">
    <%= form.label :main_image %>
    <%= form.file_field :main_image %>
</div>

<% if post.main_image.attached? %>
<p>
    <%= link_to 'Remove Main Image', "#{destroy_attachment_path(post.main_image.id)}?post_id=#{post.id}", method: 'delete', data: { confirm: 'Delete the main image attachment?' } %>
</p>

<div>Current main image: </div>
<%= image_tag post.main_image.variant(resize: '200x200') %>
<%= tag.input type: 'hidden', name: 'post[main_image]', value: post.main_image.blob.signed_id %>
<% end %>

<% post.other_images.each do |other| %>
<%= tag.input type: 'hidden', name: 'post[other_images][]', value: other.blob.signed_id %>
<% end %>

<div class="field">
    <%= form.label :body %>
    <%= form.rich_text_area :body %>
</div>

<div class="actions">
    <%= form.submit %>
</div>
<% end %>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= render "posts/form" %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Body</th>
            <th>Posted date</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @posts.each do |post| %>
        <tr>
            <td><%= post.title %></td>
            <td><%= post.body %></td>
            <td><%= link_to 'Show', post %></td>
            <td><%= link_to 'Edit', edit_post_path(post) %></td>
            <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h2>Create New Post</h2>

<%= render "posts/form" %>

app/views/posts/show.html.erb
<div class="col-sm-11 col-xs-12 blog-content">
    <h2 class="text-center"><%= @post.title %></h2>
    <h5 class="text-center"><%= @post.created_at.strftime('%b %d, %Y') %></h5>
    <p id="notice"><%= notice %></p>

    <% if @post.main_image.attached? %>
    <div class='main-img'>
        <%= image_tag @post.main_image.variant(resize: '400x400') %>
    </div>
    <% end %>
    <div><%= raw @post.body %></div>
    <%= link_to 'Edit', edit_post_path(@post) %> |
    <%= link_to 'Back', posts_path %>
</div>